Lecture-3hw
popovre/learnjs-react pull request #4
Opened 2024-01-29 12:38 UTC by popovre

2024-01-29 12:41 UTC, popovre reviewed
Возможно нагородил лишних стилей на все родительские блоки элемента <main>. 
Во вском случае мне не нравится то, сколько я нагородил стилей мб избыточно и бесполезно.

2024-01-30 11:12 UTC, SArchieEdu requested changes

2024-01-30 11:12 UTC, SArchieEdu commented on src/components/button/component.jsx
> +const Button = ({ children, disabled = false, className, onClick, id }) => {
а нужно ли нам сюда прокидывать id, если мы его обратно в колбеке отправляем

2024-01-30 11:12 UTC, SArchieEdu commented on src/components/counter/component.jsx
> +  const [incrementState, setIncrementState] = useState(count === maxValue);
эти состояния лишние, тк являются производными от count => их можно всегда вычислить и не хранить. Хранить лучше только то, что пользователь нам вводит или подобное

2024-01-30 11:12 UTC, SArchieEdu commented on src/components/restaurants/component.jsx
> +        {restaurants.map((restaurant) => {
find

2024-02-01 08:15 UTC, merged